'Copyright © exc-jdbi 2016

'© mnPassing 2016

'mnPassing - www.github.com/exc-jdbi/passing

'mnPassing is Free and Opensource Software


'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

